#Chemins personalizes
#server.servlet.context-path=/api

# Configuration du serveur
spring.application.name=sol-solution
server.port=${PORT:8071}
#server.port=${PORT:8080}


# Profile actif par default
spring.profiles.active=dev

#End point
app.env.apiUrl=${API_URL}
app.base.url=${BASE_URL}

# Configuration des uploads
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Configuration de l'application
app.upload.dir=uploads/pdfs
app.qrcode.dir=uploads/qrcodes

# Firebase Configuration
firebase.bucket-name=solsolutionpdf.firebasestorage.app
firebase.service-key-path=classpath:serviceAccountKey.json
FIREBASE_TYPE=${FIREBASE_TYPE}
FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}

# Configuration des logs
logging.level.com.qrcode.generator=DEBUG
logging.level.org.springframework.web=DEBUG

# Configuration pour servir le frontend Angular
spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/,classpath:/public/

# Configuration des emails
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Configuration Brevo SMTP
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=btbimportationservice333@gmail.com
brevo.sender.name=${BREVO_APP_NAME}

# Configuration de l'application SSAC
app.name=SSAC QR Code Application
app.version=1.0.0

# Configuration CORS pour l'API
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*



# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# 1 jour en millisecondes
application.security.jwt.expiration=86400000
#application.security.jwt.expiration=15000
# Configuration Refresh Token (7 jours en millisecondes)
jwt.refreshExpiration=604800000

